ALTER TABLE payments
  MODIFY COLUMN provider ENUM('PAYSTACK','STRIPE','FLUTTERWAVE','MONNIFY','PAYMENTPOINT','PAYVESSEL') NOT NULL;

ALTER TABLE payment_gateway_keys
  MODIFY COLUMN gateway ENUM('PAYSTACK','FLUTTERWAVE','MONNIFY','PAYMENTPOINT','PAYVESSEL') NOT NULL;

ALTER TABLE payment_gateway_webhooks
  MODIFY COLUMN gateway ENUM('PAYSTACK','FLUTTERWAVE','MONNIFY','PAYMENTPOINT','PAYVESSEL') NOT NULL;
